[ -f ~/.git-completion.bash ] && source ~/.git-completion.bash

export DOT_FILES=~/.dotfiles
source $DOT_FILES/home/bashrcstuff/prompt
source $DOT_FILES/home/bashrcstuff/aliases
source $DOT_FILES/home/bashrcstuff/complex_aliases
source $DOT_FILES/home/bashrcstuff/exports
source /usr/local/opt/chruby/share/chruby/chruby.sh
source /usr/local/opt/chruby/share/chruby/auto.sh
# time bash -i -c "echo -n"

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
