set go -=m    "guioptions, menubar, toolbar, tarrof menus, grey menus
set go -=t
set go -=T
set go -=g
set go -=l
set go -=L
set go -=R
set go -=r
set go -=b

set background=light
set guitablabel=[%N%M]\ %f

"set fuoptions=maxvert,maxhorz
"au GUIEnter * set fullscreen

set transparency=5
