set encoding=utf-8
set nocompatible
filetype off

" whitespaces
"set listchars=trail:•,nbsp:¬,tab:‹‹,precedes:«,extends:»
"set list

call plug#begin('~/.vim/plugged')

Plug '/usr/local/opt/fzf' | Plug 'junegunn/fzf.vim'
Plug 'vim-airline/vim-airline'
Plug 'scrooloose/nerdtree'
Plug 'scrooloose/nerdcommenter'
Plug 'tpope/vim-fugitive'

Plug 'mileszs/ack.vim'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-unimpaired'
Plug 'sjl/gundo.vim'
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'
Plug 'git://github.com/Townk/vim-autoclose.git'

" colorschemes
Plug 'dracula/vim'

Plug 'kchmck/vim-coffee-script'
"Plug 'benmills/vimux'

Plug 'ecomba/vim-ruby-refactoring'
Plug 'tmhedberg/matchit'
"Plug 'christoomey/vim-tmux-navigator'
Plug 'tpope/vim-rails'

"Plug 'greyblake/vim-preview'
"Bundle 'git://github.com/terryma/vim-instant-markdown'
"Plug 'majutsushi/tagbar'
call plug#end()
filetype indent on
filetype plugin on
syntax on

set background=dark
colorscheme dracula

"vim-bufonly
set rnu                        "line numbers
set nuw=5   "line number columns
set sm                 "show match
set ai                 "auto-indent
set sw=2               "shift width
set ts=2               "tabstop
set et        "expandtab, tabs=spaces
set hls       "hlsearch
set is        "incsearch
"set cul       "cursorline
set ignorecase
set smartcase
set magic
set noerrorbells
set novisualbell
set linebreak
set wrap
set ruler
set nolazyredraw

set hidden


au BufRead,BufNewFile *.hamlc set filetype=haml

set fillchars=diff:⣿

"set undodir=~/.vim/tmp/undo/
set backupdir=~/.vim/tmp/backup/
set directory=~/.vim/tmp/swap/
set nobackup

"mappings
nnoremap <Leader>d :NERDTreeToggle
let NERDTreeHijackNetrw=1
nnoremap <Leader>g :Gstatus5j
nnoremap <Leader>w :Gwrite
nnoremap <Leader>r :Gread
nnoremap <Leader>u :GundoToggle
let g:gundo_right=1

"let g:reload_on_write = 0
map <Leader>t :TlistToggle
map <Leader>yf :s/false/true/
map <Leader>yt :s/true/false/
" turn off search highlighting
nnoremap :set invhlsearch

map <Leader>gn ^Wh
set pastetoggle=<F2>

nmap <Leader>m :Rmodel
nmap <Leader>c :Rcontroller
nmap <Leader>v :Rview

nmap <Leader>D :%d
nmap <Leader>Y :%y

nmap <Leader>N ?defw*zz

inoremap jk <Esc>

cnorea w!! w !sudo tee % > /dev/null

"folding?
"mksession
"smartindent?
"spell?

"edit vimrc
map <leader>e :tabe! ~/.vimrc
map <leader>ee :tabe! ~/.gvimrc
map <leader>b :tabe! ~/.bashrc
autocmd! bufwritepost .vimrc source ~/.vimrc "reload vimrc
" only if visual
"autocmd! bufwritepost .gvimrc source ~/.gvimrc "reload vimrc

set completeopt=menuone,preview,longest

"set viminfo+=!
set viminfo='100,<50,s10,h,:0,n~/.vim/.viminfo
set wildmenu
set wildmode=list:full
set wildignore+=.git
set wildignore+=*.sw?
set wildignore+=DS_STORE

au FocusLost * :silent! wall
au VimResized * :wincmd =

set noshowmode

set laststatus=2

"set t_Co=256
let g:airline_powerline_fonts=1
let g:airline_mode_map = {
    \ '__' : '-',
    \ 'n'  : 'N',
    \ 'i'  : 'I',
    \ 'R'  : 'R',
    \ 'c'  : 'C',
    \ 'v'  : 'V',
    \ 'V'  : 'Vl',
    \ '^V' : 'Vb',
    \ 's'  : 'S',
    \ 'S'  : 'S',
    \ '^S' : 'S',
    \ }

nnoremap <Leader>h :s/:\([^ ]*\)\(\s*\)=>/\1:/g

"nnoremap <D-k> gt
"nnoremap <D-j> gT
nnoremap k :tabprevious
nnoremap j :tabnext
nnoremap Q :q
let ruby_space_errors=1
let g:tex_flavor='latex'
nnoremap ; :

nnoremap <Leader>s :w

"nnoremap <Leader>o :ZoomWin
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<tab>"
let g:UltiSnipsJumpBackwardTrigger="<s-tab>"

highlight OverLength ctermbg=red ctermfg=white guibg=#592929
match OverLength /\%101v.\+/
autocmd FileType man match NONE

if exists("$MANPAGER")
  let $MANPAGER = ""
endif
if exists("$PAGER")
  let $PAGER = ""
endif
if $VIM_CRONTAB == "true"
  set nobackup
  set nowritebackup
endif

autocmd BufReadPost fugitive://* set bufhidden=delete
highlight DiffAdd    cterm=bold ctermfg=10 ctermbg=17 gui=none guifg=bg guibg=Red
"highlight DiffDelete cterm=bold ctermfg=10 ctermbg=17 gui=none guifg=bg guibg=Red
"highlight DiffChange cterm=bold ctermfg=10 ctermbg=17 gui=none guifg=bg guibg=Red
"highlight DiffText   cterm=bold ctermfg=10 ctermbg=88 gui=none guifg=bg guibg=Red
nnoremap <Leader>A :Ag 
nnoremap  :Files
let g:ackprg = 'ag --vimgrep'
"map <C-j> <C-W>j
"map <C-k> <C-W>k
"map <C-h> <C-W>h
"map <C-l> <C-W>l
