#!/usr/local/bin/bash/
# usage:
#   generate_ctags project_name [with_gems | only_project]
#   
#   with_gems     -- regenerate tags for gems, as well as project tags
#   only_project  -- regenerate tags for project, don't append - rewrite file
#   *no options*  -- regenerate tags for project, apply gem_tags if it exists

dotfiles_dir=${DOT_FILES:?Please export \$DOT_FILES variable in your bashrc}
. $DOT_FILES/configs/generate_ctags
# sourced config:
#   ctags=path
#   projects_dir=path
tags_file=tags
gemtags_file=gem_tags
gem_paths='bundle show --paths'

project_name=${1?'Specify project name'}
project_path=$projects_dir$1/
tags_path=$project_path$tags_file
gemtags_path=$project_path$gemtags_file
append=''

if [[ $2 = 'with_gems' ]]; then
  echo Generating $gemtags_path
  cd $project_path && $gem_paths | xargs $ctags --fields=+l -R -f $gemtags_path
fi

if [[ (-e $gemtags_path) && ($2 != 'only_project') ]]; then
  echo Applying $gemtags_file
  cp $gemtags_path $tags_path
  append=-a
fi

#cp $gemtags_path $tags_path
echo Generating $tags_path
$ctags -R --fields=+l $append \
--exclude=public/ --exclude=tmp/ --exclude=.git/ \
--langdef=coffee --langmap=coffee:.coffee \
--regex-coffee="/^class ([A-Za-z.]+)( extends [A-Za-z.]+)?$/\1/c,class/" \
--regex-coffee="/^[ \t]*@?([A-Za-z.]+):.*[-=]>.*$/\1/f,function/" \
--regex-coffee="/^[ \t]*([A-Za-z.]+)[ \t]+=.*[-=]>.*$/\1/f,function/" \
--regex-coffee="/^[ \t]*([A-Za-z.]+)[ \t]+=[^->\n]*$/\1/v,variable/" \
-f $tags_path $project_path
#regex-coffee="/(^|=[ \t])*class ([A-Za-z.]+)( extends [A-Za-z.]+)?$/\2/c,class/*/"
#regex-coffee="/^[ \t]*@?([A-Za-z.]+):.*[-=]>.*$/\1/f,function/ */"
#regex-coffee="/^[ \t]*([A-Za-z.]+)[ \t]+=.*[-=]>.*$/\1/f,function/*/"
#regex-coffee="/^[ \t]*([A-Za-z.]+)[ \t]+=[^->\n]*$/\1/v,variable/*/"
