#!/usr/local/bin/bash/
# usage:
#   generate_ctags project_name [with_gems | only_project]
#   
#   with_gems     -- regenerate tags for gems, as well as project tags
#   *no options*  -- regenerate tags for project

dotfiles_dir=${DOT_FILES:?Please export \$DOT_FILES variable in your bashrc}
. $DOT_FILES/configs/generate_ctags
# sourced config:
#   ctags=path
#   projects_dir=path
gem_paths='bundle show --paths'

project_name=${1?'Specify project name'}
project_tags_file=tags
gemtags_file=gem_tags
project_path=$projects_dir$1/
project_tags_path=$project_path$project_tags_file
gemtags_path=$project_path$gemtags_file
append=''

if [[ $2 = 'with_gems' ]]; then
  echo Generating $gemtags_path
  cd $project_path && $gem_paths | xargs $ctags --fields=+l --languages=Ruby -R -f $gemtags_path
fi

echo Generating $project_tags_path
$ctags -R --fields=+l $append \
--exclude=public/ --exclude=tmp/ --exclude=.git/ --exclude=vendor/ --exclude=log/ --exclude=bin/ \
--exclude=app/asstets/stylesheets/ --exclude=app/asstets/fonts/ --exclude=app/asstets/images/ \
-f $project_tags_path $project_path

echo Generating coffeetags
coffeetags -R -a -f $project_tags_path
